include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

image: node:16.20-bookworm

stages:
  - build
  - prepare
  - publish
  - test

variables:
  FF_USE_FASTZIP: "1"

cache:
  key:
    files:
      - package.json
    prefix: ${CI_JOB_NAME}
  paths:
    - node_modules/

build:
  stage: build
  image: node:16.20-bookworm
  script:
    - npm i
    # - npm run test
    - npm run build
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - dist
      - node_modules

prepare:
  stage: prepare
  image: minds/ci:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  dependencies:
    - build

publish:docker:
  stage: publish
  image: minds/ci:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    - docker tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - master

container_scanning:
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest
