minds:
  baseUri: "https://feat-e-337-activitypub.oke.minds.io"
  pollingInterval: 30000 # 30s

image:
  repository: registry.gitlab.com/minds/infrastructure/nostr-relay
  pullPolicy: Always
  tag: '962271233'

ingress:
  host: relay.oke.minds.io
